number = {
    SOI ~
    (
        octal_number
        | binary_number
        | hex_number
        | decimal_number
        // real_number
    )
    ~ EOI
}

decimal_number = {
    size? ~ decimal_base ~ unsigned_number
    | size? ~ decimal_base ~ x_digit ~ ( "_" )
    | size? ~ decimal_base ~ z_digit ~ ( "_" )
    | unsigned_number
}
binary_number = { size? ~ binary_base ~ binary_value }
octal_number = { size? ~ octal_base ~ octal_value }
hex_number = { size? ~ hex_base ~ hex_value }

unsigned_number = { ASCII_DIGIT ~ ("_" | ASCII_DIGIT)* }
non_zero_unsigned_number = { ASCII_NONZERO_DIGIT ~ ("_" | ASCII_DIGIT)* }
size = { non_zero_unsigned_number }

binary_value = { binary_digit ~ ("_" | binary_digit)* }
octal_value = { octal_digit ~ ("_" | octal_digit)* }
hex_value = { hex_digit ~ ("_" | hex_digit)* }

decimal_base = { "'" ~ ("s" | "S")? ~ ("d" | "D") }
octal_base = { "'" ~ ("s" | "S")? ~ ("o" | "O") }
binary_base = { "'" ~ ("s" | "S")? ~ ("b" | "B") }
hex_base = { "'" ~ ("s" | "S")? ~ ("h" | "H") }

binary_digit = { x_digit | z_digit | ASCII_BIN_DIGIT }
octal_digit = { x_digit | z_digit | ASCII_OCT_DIGIT }
hex_digit = { x_digit | z_digit | ASCII_HEX_DIGIT }
x_digit = { "x" | "X" }
z_digit = { "z" | "Z" | "?" }